title = "c4 Gitleaks configuration"

[extend]
useDefault = true

[allowlist]
description = "global allow list"
regexTarget = "match"
regexes = [
  '''secret''',
  '''AWS_ACCESS_KEY_ID''',
  '''AWS_SECRET_ACCESS_KEY''',
  '''(?i)api[_-]?key''',
]
