version: '3.8'

services:
  c4-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3000"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    command: npm run dev
    depends_on:
      - c4-backend

  c4-backend:
    # ... existing backend config
    extends:
      file: docker-compose-dev.yml
      service: c4-backend

  postgres:
    # ... existing postgres config
    extends:
      file: docker-compose-dev.yml
      service: postgres
