{{- if .Values.reis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-reis-secret
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: reis
type: Opaque
stringData:
  {{- if and (eq .Values.reis.embeddings.type "azure-openai") (not .Values.reis.embeddings.azureOpenAi.existingApiKeySecret) }}
  EMBEDDINGS_AZURE_OPENAI_API_KEY: {{ .Values.reis.embeddings.azureOpenAi.apiKey | quote }}
  {{- end }}
  {{- if and (eq .Values.reis.embeddings.type "openai") (not .Values.reis.embeddings.openAi.existingApiKeySecret) }}
  EMBEDDINGS_OPENAI_API_KEY: {{ .Values.reis.embeddings.openAi.apiKey | quote }}
  {{- end }}
  {{- if and (eq .Values.reis.embeddings.type "bedrock") (not .Values.reis.embeddings.bedrock.existingAccessKeySecret) }}
  EMBEDDINGS_BEDROCK_AWS_ACCESS_KEY_ID: {{ .Values.reis.embeddings.bedrock.accessKeyId | quote }}
  EMBEDDINGS_BEDROCK_AWS_SECRET_ACCESS_KEY: {{ .Values.reis.embeddings.bedrock.secretAccessKey | quote }}
  {{- end }}
  {{- if and (eq .Values.reis.embeddings.type "nvidia") (not .Values.reis.embeddings.nvidia.existingApiKeySecret) }}
  EMBEDDINGS_NVIDIA_API_KEY: {{ .Values.reis.embeddings.nvidia.apiKey | quote }}
  {{- end }}
  {{- if and (eq .Values.reis.vectorDatabase.type "azure-ai-search") (not .Values.reis.vectorDatabase.azureAiSearch.existingApiKeySecret) }}
  STORE_AZURE_AI_SEARCH_SERVICE_API_KEY: {{ .Values.reis.vectorDatabase.azureAiSearch.apiKey | quote }}
  {{- end }}
  {{- if and (eq .Values.reis.vectorDatabase.type "pgvector") (not .Values.reis.vectorDatabase.pgVector.existingConnectionStringSecret) }}
  STORE_PGVECTOR_URL: {{ .Values.reis.vectorDatabase.pgVector.connectionString | quote }}
  {{- end}}
  {{- if and (eq .Values.reis.speechToText.type "azure-openai-whisper") (not .Values.reis.speechToText.azureOpenAiWhisper.existingApiKeySecret) }}
  STT_AZURE_OPENAI_WHISPER_API_KEY: {{ .Values.reis.speechToText.azureOpenAiWhisper.apiKey | quote }}
  {{- end }}
  {{- end }}
