version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: c4-dev-minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=secretsecret
    command: server /data