name: E2E Tests with expensive and Stress Tests
permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/e2e-complete.yaml
  schedule:
    # every day at 4 am on main branch
    - cron: "0 4 * * *"

jobs:
  build:
    uses: ./.github/workflows/build-container-images.yaml
  e2e:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chromium
          - firefox
          - webkit
        testdir:
          - expensive-tests
          - extension-tests
          - tests
    uses: ./.github/workflows/e2e-template.yaml
    with:
      browser: ${{ matrix.browser }}
      testdir: ${{ matrix.testdir }}
    secrets: inherit

  reis-stresstest:
    needs:
      - build
    uses: ./.github/workflows/reis-stresstest.yaml
