name: Helm Chart
permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/helm-chart.yaml
      - helm-chart/**
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: d3adb5/helm-unittest-action@v2

  verify-readme-and-schema-are-up-tp-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: |
          cp README.md README_original.md
          cp values.schema.json values_original.schema.json
          npx @bitnami/readme-generator-for-helm -v values.yaml -r README.md -s values.schema.json
          diff README_original.md README.md
          diff values_original.schema.json values.schema.json
        working-directory: helm-chart
