name: REI-S Stresstest

on:
  workflow_call:

defaults:
  run:
    working-directory: services/reis

jobs:
  test-stress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - run: docker network create stresstest-network
      - name: start database
        run: |
          docker run \
            -d \
            --network stresstest-network \
            --name pgvector \
            -e POSTGRES_USER="admin" \
            -e POSTGRES_PASSWORD="secret" \
            -e POSTGRES_DB="cccc" \
            pgvector/pgvector:pg16
      - uses: actions/download-artifact@v4
        with:
          name: reis
          path: /tmp/
      - name: start REIS
        run: |
          docker load --input /tmp/reis.tar
          docker run \
            -d \
            --network stresstest-network \
            --name reis \
            -p 3201:3201 \
            --cpus 2 \
            --memory 2g \
            -e WORKERS="2" \
            -e BATCH_SIZE="100" \
            -e STORE_TYPE="pgvector" \
            -e STORE_PGVECTOR_URL="postgresql+psycopg://admin:secret@pgvector:5432/cccc" \
            -e STORE_PGVECTOR_INDEX_NAME="stresstest" \
            -e EMBEDDINGS_TYPE="random-test-embeddings" \
            reis:commit-${{ github.sha }}
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: services/reis/poetry.lock
      - run: poetry install --with dev
      - name: Stresstest
        env:
          pytest_github_report: true
        run: poetry run pytest -rs --cov=rei_s --cov-report=xml --cov-report=term --stress --error-for-skips tests/stress
