name: REI-S Stresstest

on:
  workflow_call:

defaults:
  run:
    working-directory: services/reis

jobs:
  test-stress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    services:
      pgvector:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: cccc
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      reis:
        image: ghcr.io/${{ github.repository }}/reis:commit-${{ github.sha }}
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        options: >-
          --cpus 2
          --memory 2g
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
        env:
          WORKERS: 2
          BATCH_SIZE: 100
          EMBEDDINGS_TYPE: random-test-embeddings
          STORE_TYPE: pgvector
          STORE_PGVECTOR_URL: postgresql+psycopg://admin:secret@pgvector:5432/cccc
          STORE_PGVECTOR_INDEX_NAME: stresstest
        ports:
          - 3201:3201
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: services/reis/poetry.lock
      - run: poetry install --with dev
      - name: Stresstest
        env:
          pytest_github_report: true
        run: poetry run pytest -rs --cov=rei_s --cov-report=xml --cov-report=term --stress --error-for-skips tests/stress
