name: Publish Release

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - c4-genai-suite-v*

jobs:
  backend:
    uses: ./.github/workflows/backend.yaml
  e2e:
    uses: ./.github/workflows/e2e-complete.yaml
    secrets: inherit
  frontend:
    uses: ./.github/workflows/frontend.yaml
  helm-chart:
    uses: ./.github/workflows/helm-chart.yaml
  reis:
    uses: ./.github/workflows/reis.yaml
    secrets: inherit
  build-container-images:
    uses: ./.github/workflows/build-container-images.yaml
    secrets: inherit
    with:
      push-to-registry: true
      tag-prefix: ghcr.io/${{ github.repository }}/

  upstream-workflows:
    name: Upstream Workflows
    runs-on: ubuntu-latest
    needs:
      - backend
      - e2e
      - frontend
      - helm-chart
      - reis
    steps:
      - run: echo "all done"

  promote-images:
    name: Container Image Promotion
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - bundled
          - frontend
          - backend
          - reis
          - confluence-importer
    needs:
      - upstream-workflows
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_ref
        run: echo "ref_name=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

      - name: Promote Image
        run: |
          docker pull ghcr.io/${{ github.repository }}/${{ matrix.image }}:commit-${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}/${{ matrix.image }}:commit-${{ github.sha }} ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ steps.extract_ref.outputs.ref_name }}
          docker tag ghcr.io/${{ github.repository }}/${{ matrix.image }}:commit-${{ github.sha }} ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ steps.extract_ref.outputs.ref_name }}
          docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest

  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    needs:
      - upstream-workflows
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm Chart
        run: |
          helm package helm-chart/
          helm push c4-genai-suite-*.tgz oci://ghcr.io/${{ github.repository }}/charts/
